os:
- linux
language: python
cache:
  apt: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install wheel
- python setup.py build_ext --inplace
- python setup.py sdist && pip install dist/*.tar.gz
- python setup.py bdist_wheel
- pip install pytest-cov
- pip install coveralls
script:
- python -m pytest cymem --cov=cymem

after_success: coveralls
notifications:
  email: false
  slack:
    secure: VSqtxg7u4NTZRfoZqjxPRPVS92KTy/mp62egfDZ9ujTP4VPxNe15QZuTB6r/ICPgEYqBtdhLc/aetuBcemt0bHfentV0F7bz7iDY/AFQC1h1i4G0D0wKMufuqOJFw9MOp2tSpuvCVzhCxR+Ymx/F9SaeYBAiwBawce4wu+qu3lA=
